export interface FileMetadata {
  full_unc_path: string;
  file_path: string;
  file_name: string;
  parent_path: string;
  shared_folder_name: string;
  file_size: number;
  is_file: boolean;
  host: boolean;
  host_ip: string; // Assuming string based on download requirement
  host_name?: string;
}

// Read API URL from runtime config (generated by run_frontend script)
// Runtime configuration fetcher
// Port Scanner Implementation
const scanPort = async (port: number): Promise<string | null> => {
  const url = `http://localhost:${port}`;
  try {
    // Shorter timeout for faster scanning
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 200); 
    
    // Check openapi.json to confirm it's our backend (fastest check and avoids 404s)
    console.debug(`[API] Scanning ${url}...`);
    const response = await fetch(`${url}/openapi.json`, { 
      method: 'GET', // Changed to GET for better compatibility
      signal: controller.signal 
    });
    clearTimeout(timeoutId);
    
    if (response.ok) {
      console.log(`[API] SUCCESS: Found backend at port ${port}`);
      return url;
    }
  } catch (e) {
    // Ignore connection refused or timeout
    // console.debug(`[API] Failed scan on ${port}:`, e);
  }
  return null;
};

// Start scanning common ports + dynamic range
const findBackendUrl = async (): Promise<string> => {
  console.log("[API] Starting Port Scanner to find backend...");
  
  // 1. Check fixed/common ports first
  const commonPorts = [8000, 8001, 8080, 5000, 3000];
  for (const port of commonPorts) {
    const found = await scanPort(port);
    if (found) return found;
  }

  // 2. Scan dynamic ephemeral range (49152 to 65535) in batches
  const startPort = 49152;
  const endPort = 65535;
  const batchSize = 50; // Parallel requests

  for (let i = startPort; i <= endPort; i += batchSize) {
    const promises = [];
    for (let j = 0; j < batchSize && (i + j) <= endPort; j++) {
      promises.push(scanPort(i + j));
    }
    
    // potential race condition handling: if multiple resolve, pick first
    const results = await Promise.all(promises);
    const found = results.find(url => url !== null);
    if (found) return found;
  }

  console.error("[API] CRITICAL: Backend not found after scanning. Defaulting to 8000.");
  return 'http://localhost:8000';
};

// Runtime configuration fetcher with Scanner and server_connection.json support
let cachedConfig: { API_BASE_URL: string } | null = null;

const getConfig = async (): Promise<{ API_BASE_URL: string }> => {
  if (cachedConfig) return cachedConfig; // Return cached result immediately
  
  console.log("[API] getConfig called. Attempting to resolve backend URL...");

  // 1. Try server_connection.json (User Requested Method)
  // We try multiple paths since we don't know where the web server root is relative to the file.
  const potentialPaths = [
    '/server_connection.json', 
    '/backend/server_connection.json',
    '../server_connection.json',
    '../../server_connection.json' // Added extra depth
  ];

  for (const path of potentialPaths) {
    try {
      console.log(`[API] Trying to fetch config from: ${path}`);
      const response = await fetch(path);
      if (response.ok) {
        const data = await response.json();
        console.log(`[API] Successfully read ${path}:`, data);
        // data structure: { SERVER_IP: "...", PORT: ... }
        if (data.SERVER_IP && data.PORT) {
          const url = `http://${data.SERVER_IP}:${data.PORT}`;
          console.log(`[API] CONNECTED via ${path}:`, url);
          cachedConfig = { API_BASE_URL: url };
          return cachedConfig;
        }
      } else {
        console.warn(`[API] Failed to fetch ${path}: ${response.status} ${response.statusText}`);
      }
    } catch (e) {
      console.warn(`[API] Network error fetching ${path}:`, e);
    }
  }

  // 2. Try config.json (Legacy/Backup)
  try {
    console.log("[API] Trying /config.json...");
    const response = await fetch('/config.json');
    if (response.ok) {
      cachedConfig = await response.json();
      console.log("[API] CONNECTED via /config.json:", cachedConfig);
      return cachedConfig!;
    } else {
        console.warn(`[API] Failed /config.json: ${response.status}`);
    }
  } catch (error) {
    console.warn("[API] Network error fetching /config.json:", error);
  }

  // 3. Fallback: Scan ports
  console.log("[API] All config files failed. Initiating Port Scan...");
  const foundUrl = await findBackendUrl();
  cachedConfig = { API_BASE_URL: foundUrl };
  return cachedConfig;
};

export const refreshFiles = async (): Promise<any> => {
  const { API_BASE_URL } = await getConfig();
  console.log('[API] Refreshing files...', `${API_BASE_URL}/refresh/`);
  try {
    const response = await fetch(`${API_BASE_URL}/refresh/`, {
      method: 'POST',
    });
    console.log('[API] Refresh response status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('[API] Refresh failed:', response.status, errorText);
      throw new Error(`Failed to refresh files: ${response.status} ${errorText}`);
    }
    
    const data = await response.json();
    console.log('[API] Refresh success:', data);
    return data;
  } catch (error) {
    console.error('[API] Refresh error:', error);
    throw error;
  }
};

export const findFiles = async (filename?: string, directory_path?: string): Promise<FileMetadata[]> => {
  const { API_BASE_URL } = await getConfig();
  const params = new URLSearchParams();
  if (filename && filename.trim()) params.append('fileName', filename);
  if (directory_path) params.append('directory_path', directory_path);

  const url = `${API_BASE_URL}/find?${params.toString()}`;
  console.log('[API] Finding files...', url);
  try {
    const response = await fetch(url);
    if (response.status === 404 && !filename && !directory_path) {
        // Return empty list if root search returns 404
        return [];
    }
    console.log('[API] Find response status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('[API] Find failed:', response.status, errorText);
      throw new Error(`Failed to find files: ${response.status} ${errorText}`);
    }
    
    const data = await response.json();
    console.log('[API] Find success. Items found:', data.length);
    return data;
  } catch (error) {
    console.error('[API] Find error:', error);
    throw error;
  }
};

export const downloadFile = async (
  host_ip: string,
  shared_folder_name: string,
  file_path: string,
  onStart?: () => void,
  onEnd?: () => void,
  onProgress?: (percent: number) => void
): Promise<void> => {
  const { API_BASE_URL } = await getConfig();
  const url = `${API_BASE_URL}/download/`;
  const body = { host_ip, shared_folder_name, file_path };
  console.log('[API] Downloading file...', url, body);

  onStart?.();

  return new Promise<void>((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', url, true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.responseType = 'blob';

    xhr.onprogress = (event) => {
      if (event.lengthComputable) {
        const percent = Math.round((event.loaded / event.total) * 100);
        console.log(`[API] Download progress: ${percent}%`);
        onProgress?.(percent);
      } else {
        const mb = (event.loaded / 1024 / 1024).toFixed(1);
        console.log(`[API] Downloaded ${mb} MB`);
        onProgress?.(-1); // indeterminate
      }
    };

    xhr.onload = () => {
      console.log('[API] XHR Download status:', xhr.status);
      if (xhr.status === 200) {
        const blob = xhr.response;
        const urlBlob = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = urlBlob;

        // Try to get filename from Content-Disposition header
        const contentDisposition = xhr.getResponseHeader('Content-Disposition');
        let fileName = file_path.split('\\').pop()?.split('/').pop() || 'download';
        if (contentDisposition) {
          const filenameMatch = contentDisposition.match(/filename="?(.+)"?/);
          if (filenameMatch?.[1]) {
            fileName = filenameMatch[1];
          }
        }

        console.log('[API] Starting download for:', fileName);
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(urlBlob);
        document.body.removeChild(a);
        console.log('[API] Download completed successfully');
        onEnd?.();
        resolve();
      } else {
        console.error('[API] Download failed:', xhr.status, xhr.statusText);
        onEnd?.();
        reject(new Error(`Download failed: ${xhr.status} ${xhr.statusText}`));
      }
    };

    xhr.onerror = () => {
      console.error('[API] XHR Download network error');
      onEnd?.();
      reject(new Error('Network error during download'));
    };

    xhr.ontimeout = () => {
      console.error('[API] XHR Download timeout');
      onEnd?.();
      reject(new Error('Download timed out'));
    };

    xhr.send(JSON.stringify(body));
  });
};

export const previewFile = async (
  host_ip: string,
  shared_folder_name: string,
  file_path: string
): Promise<Blob> => {
  const { API_BASE_URL } = await getConfig();
  const url = `${API_BASE_URL}/download/`;
  const body = { host_ip, shared_folder_name, file_path };
  
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error('Failed to fetch preview');
  }

  return response.blob();
};
