
export interface FileMetadata {
  full_unc_path: string;
  file_path: string;
  file_name: string;
  shared_folder_name: string;
  file_size: number;
  is_file: boolean;
  host: boolean;
  host_ip: string; // Assuming string based on download requirement
  host_name?: string;
}

// Read API URL from runtime config (generated by run_frontend script)
// Falls back to localhost:8000 for development
const API_BASE_URL = (window as any).__CONFIG__?.API_URL || 'http://127.0.0.1:8000';

export const refreshFiles = async (): Promise<{ message: string }> => {
  console.log('[API] Refreshing files...', `${API_BASE_URL}/refresh/`);
  try {
    const response = await fetch(`${API_BASE_URL}/refresh/`, {
      method: 'POST',
    });
    console.log('[API] Refresh response status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('[API] Refresh failed:', response.status, errorText);
      throw new Error(`Failed to refresh files: ${response.status} ${errorText}`);
    }
    
    const data = await response.json();
    console.log('[API] Refresh success:', data);
    return data;
  } catch (error) {
    console.error('[API] Refresh error:', error);
    throw error;
  }
};

export const findFiles = async (filename: string): Promise<FileMetadata[]> => {
  const url = `${API_BASE_URL}/find?fileName=${encodeURIComponent(filename)}`;
  console.log('[API] Finding files...', url);
  try {
    const response = await fetch(url);
    console.log('[API] Find response status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('[API] Find failed:', response.status, errorText);
      throw new Error(`Failed to find files: ${response.status} ${errorText}`);
    }
    
    const data = await response.json();
    console.log('[API] Find success. Items found:', data.length, data);
    return data;
  } catch (error) {
    console.error('[API] Find error:', error);
    throw error;
  }
};

export const downloadFile = async (
  host_ip: string,
  shared_folder_name: string,
  file_path: string,
  onStart?: () => void,
  onEnd?: () => void,
  onProgress?: (percent: number) => void
): Promise<void> => {
  const url = `${API_BASE_URL}/download/`;
  const body = { host_ip, shared_folder_name, file_path };
  console.log('[API] Downloading file...', url, body);

  onStart?.();

  return new Promise<void>((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', url, true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.responseType = 'blob';

    xhr.onprogress = (event) => {
      if (event.lengthComputable) {
        const percent = Math.round((event.loaded / event.total) * 100);
        console.log(`[API] Download progress: ${percent}%`);
        onProgress?.(percent);
      } else {
        const mb = (event.loaded / 1024 / 1024).toFixed(1);
        console.log(`[API] Downloaded ${mb} MB`);
        onProgress?.(-1); // indeterminate
      }
    };

    xhr.onload = () => {
      console.log('[API] XHR Download status:', xhr.status);
      if (xhr.status === 200) {
        const blob = xhr.response;
        const urlBlob = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = urlBlob;

        // Try to get filename from Content-Disposition header
        const contentDisposition = xhr.getResponseHeader('Content-Disposition');
        let fileName = file_path.split('\\').pop()?.split('/').pop() || 'download';
        if (contentDisposition) {
          const filenameMatch = contentDisposition.match(/filename="?(.+)"?/);
          if (filenameMatch?.[1]) {
            fileName = filenameMatch[1];
          }
        }

        console.log('[API] Starting download for:', fileName);
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(urlBlob);
        document.body.removeChild(a);
        console.log('[API] Download completed successfully');
        onEnd?.();
        resolve();
      } else {
        console.error('[API] Download failed:', xhr.status, xhr.statusText);
        onEnd?.();
        reject(new Error(`Download failed: ${xhr.status} ${xhr.statusText}`));
      }
    };

    xhr.onerror = () => {
      console.error('[API] XHR Download network error');
      onEnd?.();
      reject(new Error('Network error during download'));
    };

    xhr.ontimeout = () => {
      console.error('[API] XHR Download timeout');
      onEnd?.();
      reject(new Error('Download timed out'));
    };

    xhr.send(JSON.stringify(body));
  });
};
